# Generated by Django 3.2.9 on 2021-11-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
